# Genreal options
general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 300                                # 5min.
    on-timeout = brightnessctl -s set 10         # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r                 # monitor backlight restore.
}

# Set monitor light down after 5 minutes inactivity
listener {
    timeout = 300
    on-timeout = notify-send "Monitor will be lighted down"
    on-resume = notify-send "Monitor is being lighted up"

}

# Lock screen after 10 minutes inactivity
listen {
    timeout = 600
    on-timeout = loginctl lock-session
}

# Turn off monitor after 15 minutes inactivity
listener {
    timeout = 900                                 # 15min.
    on-timeout = hyprctl dispatch dpms off        # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on          # screen on when activity is detected after timeout has fired.
}

# Suspend after 60 minutes inactivity
listener {
    timeout = 86000                               # 60min
    on-timeout = systemctl suspend                # suspend pc
}
